import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('开始添加测试数据...')

  // 清空现有数据
  await prisma.linkSubmission.deleteMany()
  await prisma.friendLinkSubmission.deleteMany()
  await prisma.link.deleteMany()
  await prisma.friendLink.deleteMany()
  await prisma.category.deleteMany()
  await prisma.user.deleteMany()
  await prisma.siteConfig.deleteMany()

  // 创建管理员用户
  const hashedPassword = await bcrypt.hash('admin123', 12)
  const admin = await prisma.user.create({
    data: {
      username: 'admin',
      email: 'admin@t-nav.com',
      password: hashedPassword,
      role: 'ADMIN',
    },
  })

  // 创建站点配置
  await prisma.siteConfig.create({
    data: {
      name: 'T-Nav 导航网站',
      description: '专门为开发者和技术爱好者设计的导航网站',
      keywords: 'T-Nav,导航网站,编程资源,开发者工具,Vue,React,AI工具',
      author: 'hb0730',
      authorLink: 'https://hb0730.me',
      url: 'https://t-nav.hb0730.me',
      logo: 'https://t-nav.hb0730.me/logo.png',
      icon: 'https://t-nav.hb0730.me/favicon.ico',
      icp: '',
      defaultLocale: 'zh-CN',
      env: 'development',
    },
  })

  // 创建分类
  const categories = [
    { title: 'AI工具', icon: 'i-tabler-robot', order: 0 },
    { title: '前端开发', icon: 'i-tabler-layout-grid-filled', order: 1 },
    { title: 'Vue生态', icon: 'i-logos-vue', order: 2 },
    { title: 'React生态', icon: 'i-logos-react', order: 3 },
    { title: '开发工具', icon: 'i-tabler-tool', order: 4 },
    { title: '设计资源', icon: 'i-tabler-palette', order: 5 },
    { title: '影视资源', icon: 'i-tabler-movie', order: 6 },
    { title: '技术博客', icon: 'i-tabler-news', order: 7 },
    { title: '图片资源', icon: 'i-tabler-photo', order: 8 },
    { title: '后端开发', icon: 'i-tabler-server', order: 9 },
    { title: 'DevOps', icon: 'i-tabler-cloud', order: 10 },
    { title: '数据库', icon: 'i-tabler-database', order: 11 },
    { title: '移动开发', icon: 'i-tabler-device-mobile', order: 12 },
    { title: '游戏开发', icon: 'i-tabler-device-gamepad', order: 13 },
    { title: '机器学习', icon: 'i-tabler-brain', order: 14 },
    { title: '区块链', icon: 'i-tabler-currency-bitcoin', order: 15 },
  ]

  const createdCategories = await Promise.all(
    categories.map(category => prisma.category.create({ data: category })),
  )

  // 创建链接数据
  const links = [
    // AI工具 (0)
    {
      title: 'ChatGPT',
      url: 'https://chat.openai.com',
      logo: 'i-simple-icons-openai',
      description: 'OpenAI开发的AI对话助手，支持多种任务和对话',
      tags: JSON.stringify(['ai', '对话', 'openai', 'chatgpt']),
      categoryId: createdCategories[0].id,
      order: 0,
    },
    {
      title: 'Claude',
      url: 'https://claude.ai',
      logo: 'i-tabler-robot-face',
      description: 'Anthropic开发的AI助手，擅长分析和推理',
      tags: JSON.stringify(['ai', '对话', 'anthropic', 'claude']),
      categoryId: createdCategories[0].id,
      order: 1,
    },
    {
      title: 'Midjourney',
      url: 'https://www.midjourney.com',
      logo: 'i-tabler-brush',
      description: '强大的AI绘画工具，生成高质量艺术图像',
      tags: JSON.stringify(['ai', '绘画', '图像生成', 'midjourney']),
      categoryId: createdCategories[0].id,
      order: 2,
    },
    {
      title: 'Stable Diffusion',
      url: 'https://stability.ai',
      logo: 'i-tabler-palette',
      description: '开源的AI图像生成模型',
      tags: JSON.stringify(['ai', '图像生成', '开源']),
      categoryId: createdCategories[0].id,
      order: 3,
    },
    {
      title: 'GitHub Copilot',
      url: 'https://github.com/features/copilot',
      logo: 'i-simple-icons-github',
      description: 'AI代码助手，提供智能代码补全',
      tags: JSON.stringify(['ai', '代码', '编程助手']),
      categoryId: createdCategories[0].id,
      order: 4,
    },
    {
      title: 'Perplexity',
      url: 'https://www.perplexity.ai',
      logo: 'i-tabler-search',
      description: 'AI搜索引擎，提供准确的答案和引用',
      tags: JSON.stringify(['ai', '搜索', '问答']),
      categoryId: createdCategories[0].id,
      order: 5,
    },
    {
      title: 'Notion AI',
      url: 'https://www.notion.so/product/ai',
      logo: 'i-simple-icons-notion',
      description: 'Notion内置的AI写作助手',
      tags: JSON.stringify(['ai', '写作', '笔记']),
      categoryId: createdCategories[0].id,
      order: 6,
    },
    {
      title: 'DeepL',
      url: 'https://www.deepl.com',
      logo: 'i-tabler-language',
      description: '高质量的AI翻译工具',
      tags: JSON.stringify(['ai', '翻译', '语言']),
      categoryId: createdCategories[0].id,
      order: 7,
    },
    {
      title: 'Cursor',
      url: 'https://cursor.sh',
      logo: 'i-tabler-cursor-text',
      description: 'AI代码编辑器，集成ChatGPT',
      tags: JSON.stringify(['ai', '编辑器', '代码']),
      categoryId: createdCategories[0].id,
      order: 8,
    },
    {
      title: 'Runway ML',
      url: 'https://runwayml.com',
      logo: 'i-tabler-video',
      description: 'AI视频生成和编辑工具',
      tags: JSON.stringify(['ai', '视频', '编辑']),
      categoryId: createdCategories[0].id,
      order: 9,
    },

    // 前端开发 (1)
    {
      title: 'MDN Web文档',
      url: 'https://developer.mozilla.org',
      logo: 'i-simple-icons-firefox',
      description: 'Web开发者最权威的文档和学习资源',
      tags: JSON.stringify(['文档', 'javascript', 'html', 'css', 'web']),
      categoryId: createdCategories[1].id,
      order: 0,
    },
    {
      title: 'Can I Use',
      url: 'https://caniuse.com',
      logo: 'i-tabler-device-desktop-check',
      description: '查询浏览器对Web技术的支持情况',
      tags: JSON.stringify(['兼容性', '浏览器', 'css', 'javascript']),
      categoryId: createdCategories[1].id,
      order: 1,
    },
    {
      title: 'CSS-Tricks',
      url: 'https://css-tricks.com',
      logo: 'i-simple-icons-css3',
      description: 'CSS技巧和前端开发资源',
      tags: JSON.stringify(['css', '技巧', '教程']),
      categoryId: createdCategories[1].id,
      order: 2,
    },
    {
      title: 'JavaScript.info',
      url: 'https://javascript.info',
      logo: 'i-simple-icons-javascript',
      description: '现代JavaScript教程',
      tags: JSON.stringify(['javascript', '教程', '学习']),
      categoryId: createdCategories[1].id,
      order: 3,
    },
    {
      title: 'Webpack',
      url: 'https://webpack.js.org',
      logo: 'i-simple-icons-webpack',
      description: '模块打包工具',
      tags: JSON.stringify(['构建工具', 'webpack', '打包']),
      categoryId: createdCategories[1].id,
      order: 4,
    },
    {
      title: 'Vite',
      url: 'https://vitejs.dev',
      logo: 'i-simple-icons-vite',
      description: '快速的前端构建工具',
      tags: JSON.stringify(['构建工具', 'vite', '快速']),
      categoryId: createdCategories[1].id,
      order: 5,
    },
    {
      title: 'Rollup',
      url: 'https://rollupjs.org',
      logo: 'i-simple-icons-rollup',
      description: 'JavaScript模块打包器',
      tags: JSON.stringify(['打包器', 'rollup', 'es模块']),
      categoryId: createdCategories[1].id,
      order: 6,
    },
    {
      title: 'Parcel',
      url: 'https://parceljs.org',
      logo: 'i-simple-icons-parcel',
      description: '零配置的Web应用打包工具',
      tags: JSON.stringify(['打包工具', 'parcel', '零配置']),
      categoryId: createdCategories[1].id,
      order: 7,
    },
    {
      title: 'esbuild',
      url: 'https://esbuild.github.io',
      logo: 'i-tabler-bolt',
      description: '极速JavaScript打包器',
      tags: JSON.stringify(['打包器', 'esbuild', '快速']),
      categoryId: createdCategories[1].id,
      order: 8,
    },
    {
      title: 'SWC',
      url: 'https://swc.rs',
      logo: 'i-tabler-speedboat',
      description: 'Rust编写的JavaScript/TypeScript编译器',
      tags: JSON.stringify(['编译器', 'swc', 'rust']),
      categoryId: createdCategories[1].id,
      order: 9,
    },

    // Vue生态 (2)
    {
      title: 'Vue.js',
      url: 'https://cn.vuejs.org',
      logo: 'i-simple-icons-vue-dot-js',
      description: '渐进式JavaScript框架',
      tags: JSON.stringify(['vue', '框架', 'javascript', '前端']),
      categoryId: createdCategories[2].id,
      order: 0,
    },
    {
      title: 'Nuxt.js',
      url: 'https://nuxt.com',
      logo: 'i-simple-icons-nuxt-dot-js',
      description: 'Vue.js全栈框架，支持SSR和静态生成',
      tags: JSON.stringify(['nuxt', 'vue', 'ssr', '全栈']),
      categoryId: createdCategories[2].id,
      order: 1,
    },
    {
      title: 'VueUse',
      url: 'https://vueuse.org',
      logo: 'i-tabler-puzzle',
      description: 'Vue组合式API工具集合',
      tags: JSON.stringify(['vue', 'composables', 'utils', 'hooks']),
      categoryId: createdCategories[2].id,
      order: 2,
    },
    {
      title: 'Quasar',
      url: 'https://quasar.dev',
      logo: 'i-simple-icons-quasar',
      description: 'Vue.js跨平台框架',
      tags: JSON.stringify(['vue', 'quasar', '跨平台']),
      categoryId: createdCategories[2].id,
      order: 3,
    },
    {
      title: 'Vuetify',
      url: 'https://vuetifyjs.com',
      logo: 'i-simple-icons-vuetify',
      description: 'Vue.js Material Design组件库',
      tags: JSON.stringify(['vue', 'vuetify', 'material-design']),
      categoryId: createdCategories[2].id,
      order: 4,
    },
    {
      title: 'Element Plus',
      url: 'https://element-plus.org',
      logo: 'i-tabler-components',
      description: 'Vue 3组件库',
      tags: JSON.stringify(['vue', 'element-plus', '组件库']),
      categoryId: createdCategories[2].id,
      order: 5,
    },
    {
      title: 'Ant Design Vue',
      url: 'https://antdv.com',
      logo: 'i-simple-icons-antdesign',
      description: 'Ant Design的Vue实现',
      tags: JSON.stringify(['vue', 'ant-design', '组件库']),
      categoryId: createdCategories[2].id,
      order: 6,
    },
    {
      title: 'Naive UI',
      url: 'https://www.naiveui.com',
      logo: 'i-tabler-leaf',
      description: 'Vue 3组件库，TypeScript友好',
      tags: JSON.stringify(['vue', 'naive-ui', 'typescript']),
      categoryId: createdCategories[2].id,
      order: 7,
    },
    {
      title: 'Vuepress',
      url: 'https://vuepress.vuejs.org',
      logo: 'i-tabler-book',
      description: 'Vue驱动的静态网站生成器',
      tags: JSON.stringify(['vue', 'vuepress', '文档']),
      categoryId: createdCategories[2].id,
      order: 8,
    },
    {
      title: 'Gridsome',
      url: 'https://gridsome.org',
      logo: 'i-tabler-grid-dots',
      description: 'Vue.js静态站点生成器',
      tags: JSON.stringify(['vue', 'gridsome', '静态站点']),
      categoryId: createdCategories[2].id,
      order: 9,
    },

    // React生态 (3)
    {
      title: 'React',
      url: 'https://react.dev',
      logo: 'i-simple-icons-react',
      description: '用于构建用户界面的JavaScript库',
      tags: JSON.stringify(['react', '框架', 'javascript', '前端']),
      categoryId: createdCategories[3].id,
      order: 0,
    },
    {
      title: 'Next.js',
      url: 'https://nextjs.org',
      logo: 'i-simple-icons-next-dot-js',
      description: 'React全栈框架，支持SSR和静态生成',
      tags: JSON.stringify(['nextjs', 'react', 'ssr', '全栈']),
      categoryId: createdCategories[3].id,
      order: 1,
    },
    {
      title: 'React Router',
      url: 'https://reactrouter.com',
      logo: 'i-tabler-route',
      description: 'React应用的声明式路由',
      tags: JSON.stringify(['react', 'router', '路由', 'spa']),
      categoryId: createdCategories[3].id,
      order: 2,
    },
    {
      title: 'Gatsby',
      url: 'https://www.gatsbyjs.com',
      logo: 'i-simple-icons-gatsby',
      description: 'React静态站点生成器',
      tags: JSON.stringify(['react', 'gatsby', '静态站点']),
      categoryId: createdCategories[3].id,
      order: 3,
    },
    {
      title: 'Create React App',
      url: 'https://create-react-app.dev',
      logo: 'i-tabler-rocket',
      description: 'React应用脚手架',
      tags: JSON.stringify(['react', 'cra', '脚手架']),
      categoryId: createdCategories[3].id,
      order: 4,
    },
    {
      title: 'Material-UI',
      url: 'https://mui.com',
      logo: 'i-simple-icons-mui',
      description: 'React Material Design组件库',
      tags: JSON.stringify(['react', 'material-ui', '组件库']),
      categoryId: createdCategories[3].id,
      order: 5,
    },
    {
      title: 'Ant Design',
      url: 'https://ant.design',
      logo: 'i-simple-icons-antdesign',
      description: 'React UI设计语言和组件库',
      tags: JSON.stringify(['react', 'ant-design', '组件库']),
      categoryId: createdCategories[3].id,
      order: 6,
    },
    {
      title: 'Chakra UI',
      url: 'https://chakra-ui.com',
      logo: 'i-tabler-om',
      description: 'React的简单、模块化组件库',
      tags: JSON.stringify(['react', 'chakra-ui', '组件库']),
      categoryId: createdCategories[3].id,
      order: 7,
    },
    {
      title: 'React Query',
      url: 'https://tanstack.com/query',
      logo: 'i-tabler-database-search',
      description: 'React数据获取库',
      tags: JSON.stringify(['react', 'react-query', '数据获取']),
      categoryId: createdCategories[3].id,
      order: 8,
    },
    {
      title: 'React Hook Form',
      url: 'https://react-hook-form.com',
      logo: 'i-tabler-forms',
      description: '高性能、灵活的React表单库',
      tags: JSON.stringify(['react', '表单', 'hooks']),
      categoryId: createdCategories[3].id,
      order: 9,
    },

    // 开发工具 (4)
    {
      title: 'GitHub',
      url: 'https://github.com',
      logo: 'i-simple-icons-github',
      description: '全球最大的开源代码托管平台',
      tags: JSON.stringify(['git', '代码托管', '开源', '协作']),
      categoryId: createdCategories[4].id,
      order: 0,
    },
    {
      title: 'Visual Studio Code',
      url: 'https://code.visualstudio.com',
      logo: 'i-simple-icons-visualstudiocode',
      description: '轻量级代码编辑器',
      tags: JSON.stringify(['编辑器', 'vscode', '代码']),
      categoryId: createdCategories[4].id,
      order: 1,
    },
    {
      title: 'GitLab',
      url: 'https://gitlab.com',
      logo: 'i-simple-icons-gitlab',
      description: 'DevOps平台和Git仓库管理',
      tags: JSON.stringify(['git', 'gitlab', 'devops']),
      categoryId: createdCategories[4].id,
      order: 2,
    },
    {
      title: 'Figma',
      url: 'https://www.figma.com',
      logo: 'i-simple-icons-figma',
      description: '在线协作设计工具',
      tags: JSON.stringify(['设计', 'figma', '协作']),
      categoryId: createdCategories[4].id,
      order: 3,
    },
    {
      title: 'Postman',
      url: 'https://www.postman.com',
      logo: 'i-simple-icons-postman',
      description: 'API开发和测试平台',
      tags: JSON.stringify(['api', 'postman', '测试']),
      categoryId: createdCategories[4].id,
      order: 4,
    },
    {
      title: 'Insomnia',
      url: 'https://insomnia.rest',
      logo: 'i-simple-icons-insomnia',
      description: 'REST API客户端',
      tags: JSON.stringify(['api', 'insomnia', 'rest']),
      categoryId: createdCategories[4].id,
      order: 5,
    },
    {
      title: 'JetBrains',
      url: 'https://www.jetbrains.com',
      logo: 'i-simple-icons-jetbrains',
      description: '专业开发工具套件',
      tags: JSON.stringify(['ide', 'jetbrains', '开发工具']),
      categoryId: createdCategories[4].id,
      order: 6,
    },
    {
      title: 'Sourcetree',
      url: 'https://www.sourcetreeapp.com',
      logo: 'i-simple-icons-sourcetree',
      description: 'Git图形化客户端',
      tags: JSON.stringify(['git', 'sourcetree', '客户端']),
      categoryId: createdCategories[4].id,
      order: 7,
    },
    {
      title: 'Docker',
      url: 'https://www.docker.com',
      logo: 'i-simple-icons-docker',
      description: '容器化平台',
      tags: JSON.stringify(['容器', 'docker', 'devops']),
      categoryId: createdCategories[4].id,
      order: 8,
    },
    {
      title: 'npm',
      url: 'https://www.npmjs.com',
      logo: 'i-simple-icons-npm',
      description: 'JavaScript包管理器',
      tags: JSON.stringify(['包管理', 'npm', 'javascript']),
      categoryId: createdCategories[4].id,
      order: 9,
    },

    // 设计资源 (5)
    {
      title: 'Dribbble',
      url: 'https://dribbble.com',
      logo: 'i-simple-icons-dribbble',
      description: '设计师作品展示平台',
      tags: JSON.stringify(['设计', 'dribbble', '作品集']),
      categoryId: createdCategories[5].id,
      order: 0,
    },
    {
      title: 'Behance',
      url: 'https://www.behance.net',
      logo: 'i-simple-icons-behance',
      description: 'Adobe创意作品展示平台',
      tags: JSON.stringify(['设计', 'behance', 'adobe']),
      categoryId: createdCategories[5].id,
      order: 1,
    },
    {
      title: 'Unsplash',
      url: 'https://unsplash.com',
      logo: 'i-simple-icons-unsplash',
      description: '免费高质量图片资源',
      tags: JSON.stringify(['图片', 'unsplash', '免费']),
      categoryId: createdCategories[5].id,
      order: 2,
    },
    {
      title: 'Pexels',
      url: 'https://www.pexels.com',
      logo: 'i-simple-icons-pexels',
      description: '免费股票照片和视频',
      tags: JSON.stringify(['图片', 'pexels', '视频']),
      categoryId: createdCategories[5].id,
      order: 3,
    },
    {
      title: 'Adobe Color',
      url: 'https://color.adobe.com',
      logo: 'i-simple-icons-adobe',
      description: '色彩搭配和调色板工具',
      tags: JSON.stringify(['颜色', 'adobe', '调色板']),
      categoryId: createdCategories[5].id,
      order: 4,
    },
    {
      title: 'Coolors',
      url: 'https://coolors.co',
      logo: 'i-tabler-palette',
      description: '在线调色板生成器',
      tags: JSON.stringify(['颜色', 'coolors', '调色板']),
      categoryId: createdCategories[5].id,
      order: 5,
    },
    {
      title: 'Google Fonts',
      url: 'https://fonts.google.com',
      logo: 'i-simple-icons-googlefonts',
      description: '免费Web字体库',
      tags: JSON.stringify(['字体', 'google', 'fonts']),
      categoryId: createdCategories[5].id,
      order: 6,
    },
    {
      title: 'Font Awesome',
      url: 'https://fontawesome.com',
      logo: 'i-simple-icons-fontawesome',
      description: '图标字体库',
      tags: JSON.stringify(['图标', 'fontawesome', '字体']),
      categoryId: createdCategories[5].id,
      order: 7,
    },
    {
      title: 'Heroicons',
      url: 'https://heroicons.com',
      logo: 'i-tabler-icons',
      description: 'Tailwind CSS团队制作的SVG图标',
      tags: JSON.stringify(['图标', 'heroicons', 'svg']),
      categoryId: createdCategories[5].id,
      order: 8,
    },
    {
      title: 'Feather Icons',
      url: 'https://feathericons.com',
      logo: 'i-tabler-feather',
      description: '简洁美观的开源图标',
      tags: JSON.stringify(['图标', 'feather', '开源']),
      categoryId: createdCategories[5].id,
      order: 9,
    },

    // 后端开发 (9)
    {
      title: 'Node.js',
      url: 'https://nodejs.org',
      logo: 'i-simple-icons-node-dot-js',
      description: 'JavaScript运行时环境',
      tags: JSON.stringify(['nodejs', 'javascript', '后端']),
      categoryId: createdCategories[9].id,
      order: 0,
    },
    {
      title: 'Express.js',
      url: 'https://expressjs.com',
      logo: 'i-simple-icons-express',
      description: 'Node.js Web应用框架',
      tags: JSON.stringify(['express', 'nodejs', '框架']),
      categoryId: createdCategories[9].id,
      order: 1,
    },
    {
      title: 'NestJS',
      url: 'https://nestjs.com',
      logo: 'i-simple-icons-nestjs',
      description: 'Node.js企业级应用框架',
      tags: JSON.stringify(['nestjs', 'nodejs', '企业级']),
      categoryId: createdCategories[9].id,
      order: 2,
    },
    {
      title: 'Spring Boot',
      url: 'https://spring.io/projects/spring-boot',
      logo: 'i-simple-icons-springboot',
      description: 'Java微服务框架',
      tags: JSON.stringify(['spring', 'java', '微服务']),
      categoryId: createdCategories[9].id,
      order: 3,
    },
    {
      title: 'Django',
      url: 'https://www.djangoproject.com',
      logo: 'i-simple-icons-django',
      description: 'Python Web框架',
      tags: JSON.stringify(['django', 'python', 'web']),
      categoryId: createdCategories[9].id,
      order: 4,
    },
    {
      title: 'FastAPI',
      url: 'https://fastapi.tiangolo.com',
      logo: 'i-simple-icons-fastapi',
      description: '现代Python Web框架',
      tags: JSON.stringify(['fastapi', 'python', '现代']),
      categoryId: createdCategories[9].id,
      order: 5,
    },
    {
      title: 'Laravel',
      url: 'https://laravel.com',
      logo: 'i-simple-icons-laravel',
      description: 'PHP Web应用框架',
      tags: JSON.stringify(['laravel', 'php', 'web']),
      categoryId: createdCategories[9].id,
      order: 6,
    },
    {
      title: 'Ruby on Rails',
      url: 'https://rubyonrails.org',
      logo: 'i-simple-icons-rubyonrails',
      description: 'Ruby Web应用框架',
      tags: JSON.stringify(['rails', 'ruby', 'web']),
      categoryId: createdCategories[9].id,
      order: 7,
    },
    {
      title: 'ASP.NET Core',
      url: 'https://dotnet.microsoft.com/apps/aspnet',
      logo: 'i-simple-icons-dotnet',
      description: 'Microsoft .NET Web框架',
      tags: JSON.stringify(['aspnet', 'dotnet', 'microsoft']),
      categoryId: createdCategories[9].id,
      order: 8,
    },
    {
      title: 'Go Gin',
      url: 'https://gin-gonic.com',
      logo: 'i-simple-icons-go',
      description: 'Go Web框架',
      tags: JSON.stringify(['gin', 'go', 'web']),
      categoryId: createdCategories[9].id,
      order: 9,
    },

    // DevOps (10)
    {
      title: 'Kubernetes',
      url: 'https://kubernetes.io',
      logo: 'i-simple-icons-kubernetes',
      description: '容器编排平台',
      tags: JSON.stringify(['kubernetes', '容器', '编排']),
      categoryId: createdCategories[10].id,
      order: 0,
    },
    {
      title: 'Jenkins',
      url: 'https://www.jenkins.io',
      logo: 'i-simple-icons-jenkins',
      description: '开源自动化服务器',
      tags: JSON.stringify(['jenkins', 'ci/cd', '自动化']),
      categoryId: createdCategories[10].id,
      order: 1,
    },
    {
      title: 'GitLab CI',
      url: 'https://docs.gitlab.com/ee/ci/',
      logo: 'i-simple-icons-gitlab',
      description: 'GitLab持续集成',
      tags: JSON.stringify(['gitlab', 'ci/cd', '持续集成']),
      categoryId: createdCategories[10].id,
      order: 2,
    },
    {
      title: 'GitHub Actions',
      url: 'https://github.com/features/actions',
      logo: 'i-simple-icons-githubactions',
      description: 'GitHub自动化工作流',
      tags: JSON.stringify(['github', 'actions', '自动化']),
      categoryId: createdCategories[10].id,
      order: 3,
    },
    {
      title: 'Terraform',
      url: 'https://www.terraform.io',
      logo: 'i-simple-icons-terraform',
      description: '基础设施即代码工具',
      tags: JSON.stringify(['terraform', 'iac', '基础设施']),
      categoryId: createdCategories[10].id,
      order: 4,
    },
    {
      title: 'Ansible',
      url: 'https://www.ansible.com',
      logo: 'i-simple-icons-ansible',
      description: '自动化配置管理工具',
      tags: JSON.stringify(['ansible', '配置管理', '自动化']),
      categoryId: createdCategories[10].id,
      order: 5,
    },
    {
      title: 'Prometheus',
      url: 'https://prometheus.io',
      logo: 'i-simple-icons-prometheus',
      description: '监控和告警系统',
      tags: JSON.stringify(['prometheus', '监控', '告警']),
      categoryId: createdCategories[10].id,
      order: 6,
    },
    {
      title: 'Grafana',
      url: 'https://grafana.com',
      logo: 'i-simple-icons-grafana',
      description: '数据可视化平台',
      tags: JSON.stringify(['grafana', '可视化', '监控']),
      categoryId: createdCategories[10].id,
      order: 7,
    },
    {
      title: 'Nginx',
      url: 'https://nginx.org',
      logo: 'i-simple-icons-nginx',
      description: 'Web服务器和反向代理',
      tags: JSON.stringify(['nginx', 'web服务器', '代理']),
      categoryId: createdCategories[10].id,
      order: 8,
    },
    {
      title: 'Apache',
      url: 'https://httpd.apache.org',
      logo: 'i-simple-icons-apache',
      description: 'HTTP服务器',
      tags: JSON.stringify(['apache', 'http', '服务器']),
      categoryId: createdCategories[10].id,
      order: 9,
    },

    // 数据库 (11)
    {
      title: 'MySQL',
      url: 'https://www.mysql.com',
      logo: 'i-simple-icons-mysql',
      description: '开源关系型数据库',
      tags: JSON.stringify(['mysql', '数据库', '关系型']),
      categoryId: createdCategories[11].id,
      order: 0,
    },
    {
      title: 'PostgreSQL',
      url: 'https://www.postgresql.org',
      logo: 'i-simple-icons-postgresql',
      description: '先进的开源关系型数据库',
      tags: JSON.stringify(['postgresql', '数据库', '关系型']),
      categoryId: createdCategories[11].id,
      order: 1,
    },
    {
      title: 'MongoDB',
      url: 'https://www.mongodb.com',
      logo: 'i-simple-icons-mongodb',
      description: 'NoSQL文档数据库',
      tags: JSON.stringify(['mongodb', '数据库', 'nosql']),
      categoryId: createdCategories[11].id,
      order: 2,
    },
    {
      title: 'Redis',
      url: 'https://redis.io',
      logo: 'i-simple-icons-redis',
      description: '内存数据结构存储',
      tags: JSON.stringify(['redis', '缓存', '内存']),
      categoryId: createdCategories[11].id,
      order: 3,
    },
    {
      title: 'Elasticsearch',
      url: 'https://www.elastic.co',
      logo: 'i-simple-icons-elasticsearch',
      description: '分布式搜索引擎',
      tags: JSON.stringify(['elasticsearch', '搜索', '分布式']),
      categoryId: createdCategories[11].id,
      order: 4,
    },
    {
      title: 'SQLite',
      url: 'https://www.sqlite.org',
      logo: 'i-simple-icons-sqlite',
      description: '轻量级嵌入式数据库',
      tags: JSON.stringify(['sqlite', '数据库', '嵌入式']),
      categoryId: createdCategories[11].id,
      order: 5,
    },
    {
      title: 'MariaDB',
      url: 'https://mariadb.org',
      logo: 'i-simple-icons-mariadb',
      description: 'MySQL的开源分支',
      tags: JSON.stringify(['mariadb', '数据库', '开源']),
      categoryId: createdCategories[11].id,
      order: 6,
    },
    {
      title: 'CouchDB',
      url: 'https://couchdb.apache.org',
      logo: 'i-simple-icons-apachecouchdb',
      description: 'Apache NoSQL数据库',
      tags: JSON.stringify(['couchdb', 'nosql', 'apache']),
      categoryId: createdCategories[11].id,
      order: 7,
    },
    {
      title: 'InfluxDB',
      url: 'https://www.influxdata.com',
      logo: 'i-simple-icons-influxdb',
      description: '时间序列数据库',
      tags: JSON.stringify(['influxdb', '时间序列', '数据库']),
      categoryId: createdCategories[11].id,
      order: 8,
    },
    {
      title: 'Neo4j',
      url: 'https://neo4j.com',
      logo: 'i-simple-icons-neo4j',
      description: '图数据库',
      tags: JSON.stringify(['neo4j', '图数据库', 'graph']),
      categoryId: createdCategories[11].id,
      order: 9,
    },

    // 移动开发 (12)
    {
      title: 'React Native',
      url: 'https://reactnative.dev',
      logo: 'i-simple-icons-react',
      description: '跨平台移动应用开发框架',
      tags: JSON.stringify(['react-native', '移动开发', '跨平台']),
      categoryId: createdCategories[12].id,
      order: 0,
    },
    {
      title: 'Flutter',
      url: 'https://flutter.dev',
      logo: 'i-simple-icons-flutter',
      description: 'Google跨平台UI框架',
      tags: JSON.stringify(['flutter', 'dart', '跨平台']),
      categoryId: createdCategories[12].id,
      order: 1,
    },
    {
      title: 'Ionic',
      url: 'https://ionicframework.com',
      logo: 'i-simple-icons-ionic',
      description: '混合移动应用开发框架',
      tags: JSON.stringify(['ionic', '混合应用', '移动开发']),
      categoryId: createdCategories[12].id,
      order: 2,
    },
    {
      title: 'Xamarin',
      url: 'https://dotnet.microsoft.com/apps/xamarin',
      logo: 'i-simple-icons-xamarin',
      description: 'Microsoft跨平台移动开发',
      tags: JSON.stringify(['xamarin', 'microsoft', '跨平台']),
      categoryId: createdCategories[12].id,
      order: 3,
    },
    {
      title: 'Cordova',
      url: 'https://cordova.apache.org',
      logo: 'i-simple-icons-apachecordova',
      description: '混合移动应用平台',
      tags: JSON.stringify(['cordova', '混合应用', 'apache']),
      categoryId: createdCategories[12].id,
      order: 4,
    },
    {
      title: 'NativeScript',
      url: 'https://nativescript.org',
      logo: 'i-simple-icons-nativescript',
      description: '跨平台原生移动开发',
      tags: JSON.stringify(['nativescript', '原生', '跨平台']),
      categoryId: createdCategories[12].id,
      order: 5,
    },
    {
      title: 'Android Studio',
      url: 'https://developer.android.com/studio',
      logo: 'i-simple-icons-androidstudio',
      description: 'Android官方开发IDE',
      tags: JSON.stringify(['android', 'studio', 'ide']),
      categoryId: createdCategories[12].id,
      order: 6,
    },
    {
      title: 'Xcode',
      url: 'https://developer.apple.com/xcode/',
      logo: 'i-simple-icons-xcode',
      description: 'iOS和macOS开发IDE',
      tags: JSON.stringify(['xcode', 'ios', 'macos']),
      categoryId: createdCategories[12].id,
      order: 7,
    },
    {
      title: 'Swift',
      url: 'https://swift.org',
      logo: 'i-simple-icons-swift',
      description: 'Apple开发的编程语言',
      tags: JSON.stringify(['swift', 'apple', '编程语言']),
      categoryId: createdCategories[12].id,
      order: 8,
    },
    {
      title: 'Kotlin',
      url: 'https://kotlinlang.org',
      logo: 'i-simple-icons-kotlin',
      description: 'JetBrains开发的现代编程语言',
      tags: JSON.stringify(['kotlin', 'jetbrains', 'android']),
      categoryId: createdCategories[12].id,
      order: 9,
    },

    // 设计资源图片 (8)
    {
      title: 'Wallhaven',
      url: 'https://wallhaven.cc',
      logo: 'i-tabler-photo',
      description: '高质量壁纸资源网站',
      tags: JSON.stringify(['壁纸', '设计', '图片', '高清']),
      categoryId: createdCategories[8].id,
      order: 0,
    },
    {
      title: 'Pixabay',
      url: 'https://pixabay.com',
      logo: 'i-simple-icons-pixabay',
      description: '免费图片和视频资源',
      tags: JSON.stringify(['图片', 'pixabay', '免费']),
      categoryId: createdCategories[8].id,
      order: 1,
    },
    {
      title: 'Freepik',
      url: 'https://www.freepik.com',
      logo: 'i-simple-icons-freepik',
      description: '免费矢量图和设计资源',
      tags: JSON.stringify(['矢量图', 'freepik', '设计']),
      categoryId: createdCategories[8].id,
      order: 2,
    },
    {
      title: 'Getty Images',
      url: 'https://www.gettyimages.com',
      logo: 'i-tabler-camera',
      description: '专业图片和视频库',
      tags: JSON.stringify(['图片', '专业', '商用']),
      categoryId: createdCategories[8].id,
      order: 3,
    },
    {
      title: 'Shutterstock',
      url: 'https://www.shutterstock.com',
      logo: 'i-simple-icons-shutterstock',
      description: '股票图片和视频平台',
      tags: JSON.stringify(['图片', 'shutterstock', '商用']),
      categoryId: createdCategories[8].id,
      order: 4,
    },
    {
      title: 'Lorem Picsum',
      url: 'https://picsum.photos',
      logo: 'i-tabler-photo-question',
      description: '随机占位图片生成器',
      tags: JSON.stringify(['占位图', '随机', '生成器']),
      categoryId: createdCategories[8].id,
      order: 5,
    },
    {
      title: 'Placeholder.com',
      url: 'https://placeholder.com',
      logo: 'i-tabler-rectangle',
      description: '占位图片生成服务',
      tags: JSON.stringify(['占位图', '生成器', '开发']),
      categoryId: createdCategories[8].id,
      order: 6,
    },
    {
      title: 'TinyPNG',
      url: 'https://tinypng.com',
      logo: 'i-tabler-file-zip',
      description: '图片压缩工具',
      tags: JSON.stringify(['图片压缩', 'tinypng', '优化']),
      categoryId: createdCategories[8].id,
      order: 7,
    },
    {
      title: 'Remove.bg',
      url: 'https://www.remove.bg',
      logo: 'i-tabler-eraser',
      description: 'AI自动抠图工具',
      tags: JSON.stringify(['抠图', 'ai', '背景去除']),
      categoryId: createdCategories[8].id,
      order: 8,
    },
    {
      title: 'Canva',
      url: 'https://www.canva.com',
      logo: 'i-simple-icons-canva',
      description: '在线设计工具',
      tags: JSON.stringify(['设计', 'canva', '在线']),
      categoryId: createdCategories[8].id,
      order: 9,
    },
  ]

  await Promise.all(
    links.map(link => prisma.link.create({ data: link })),
  )

  // 创建友链
  const friendLinks = [
    {
      title: 'hb0730\'s Blog',
      url: 'https://hb0730.me',
      logo: 'https://hb0730.me/favicon.ico',
      description: '个人技术博客，分享开发经验和技术心得',
      order: 0,
    },
    {
      title: 'Vue.js官网',
      url: 'https://cn.vuejs.org',
      logo: 'https://cn.vuejs.org/logo.svg',
      description: 'Vue.js官方中文网站',
      order: 1,
    },
    {
      title: 'Nuxt.js',
      url: 'https://nuxt.com',
      logo: 'https://nuxt.com/icon.png',
      description: 'Vue.js全栈框架',
      order: 2,
    },
  ]

  await Promise.all(
    friendLinks.map(friendLink => prisma.friendLink.create({ data: friendLink })),
  )

  // 创建友链申请记录
  const friendLinkSubmissions = [
    {
      title: '前端技术站',
      url: 'https://frontend-tech.com',
      logo: 'https://frontend-tech.com/favicon.ico',
      description: '专注前端技术分享的技术博客',
      contact: 'admin@frontend-tech.com',
      status: 'pending',
    },
    {
      title: 'DevTools集合',
      url: 'https://devtools-collection.com',
      logo: 'https://devtools-collection.com/favicon.ico',
      description: '开发者工具和资源集合网站',
      contact: 'contact@devtools-collection.com',
      status: 'approved',
    },
    {
      title: '设计师资源库',
      url: 'https://design-resources.com',
      logo: 'https://design-resources.com/favicon.ico',
      description: '设计师必备资源和工具',
      contact: 'hello@design-resources.com',
      status: 'rejected',
      reason: '网站内容与本站主题不符',
    },
  ]

  await Promise.all(
    friendLinkSubmissions.map(submission =>
      prisma.friendLinkSubmission.create({ data: submission }),
    ),
  )

  // 创建链接申请记录
  const linkSubmissions = [
    {
      title: 'Vite',
      url: 'https://vitejs.dev',
      logo: 'https://vitejs.dev/logo.svg',
      description: '下一代前端构建工具',
      categoryId: createdCategories[1].id,
      tags: JSON.stringify(['构建工具', 'vite', '前端', 'javascript']),
      contact: 'user@example.com',
      status: 'pending',
    },
    {
      title: 'TypeScript',
      url: 'https://www.typescriptlang.org',
      logo: 'https://www.typescriptlang.org/favicon-32x32.png',
      description: 'JavaScript的超集，添加了静态类型定义',
      categoryId: createdCategories[1].id,
      tags: JSON.stringify(['typescript', 'javascript', '类型检查']),
      contact: 'developer@example.com',
      status: 'approved',
    },
    {
      title: '某个过时工具',
      url: 'https://outdated-tool.com',
      logo: 'https://outdated-tool.com/favicon.ico',
      description: '已经过时的开发工具',
      categoryId: createdCategories[4].id,
      tags: JSON.stringify(['工具', '已过时']),
      contact: 'old@example.com',
      status: 'rejected',
      reason: '工具已过时，不推荐使用',
    },
  ]

  await Promise.all(
    linkSubmissions.map(submission =>
      prisma.linkSubmission.create({ data: submission }),
    ),
  )

  console.log('✅ 测试数据添加完成！')
  console.log('')
  console.log('📊 创建的数据统计：')
  console.log(`   👤 用户: 1个`)
  console.log(`   📂 分类: ${categories.length}个`)
  console.log(`   🔗 链接: ${links.length}个`)
  console.log(`   💞 友链: ${friendLinks.length}个`)
  console.log(`   📋 友链申请: ${friendLinkSubmissions.length}个`)
  console.log(`   📝 链接申请: ${linkSubmissions.length}个`)
  console.log('')
  console.log('🔑 默认管理员账号: admin / admin123')
  console.log('')
  console.log('🎯 测试场景覆盖：')
  console.log('   ✅ 分类过多场景 (16个分类)')
  console.log('   ✅ 链接过多场景 (每个分类10个链接)')
  console.log('   ✅ 懒加载测试 (前3个分类立即加载，其余懒加载)')
  console.log('   ✅ 分类折叠测试 (每个分类显示8个链接，可展开更多)')
  console.log('   ✅ 响应式测试 (移动端4个链接，桌面端8个链接)')
  console.log('')
  console.log('🚀 可以开始测试Website组件优化效果了！')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
